"""
Django settings for prj_sgm project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
               
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '()-+1_52o844$@b6vpdtz1d!q+c*0c9p8gl%wymh_rv2#9x)d4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ngrok 사용을 위해 모든 ip 허용
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    #'suit', # admin-page customizing
    'apis.apps.SuitConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# 추가되는 앱들은 여기에. 
INSTALLED_APPS += [
    'rest_framework',
    'corsheaders', # cors header 추가, > pip3 install django-cors-headers  
    'apis',
]
# rest_framework permission 추가
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware'
]

# rest_framework 관련 middlewares 추가
MIDDLEWARE += [
    'corsheaders.middleware.CorsMiddleware',     
    'django.middleware.common.CommonMiddleware', 
]

ROOT_URLCONF = 'prj_sgm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prj_sgm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "djongo",
        "CLIENT": {
            "host": "mongodb+srv://admin:admin@cluster0.kjrlb.mongodb.net/pnu_sgm_platformdata?retryWrites=true&w=majority",
            "username": "admin",
            "password": "admin",
            "name": "pnu_sgm_platformdata",
            "authMechanism": "SCRAM-SHA-1",
        },
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "djongo",
#         "CLIENT": {
#             "host": "mongodb+srv://user1:start3we@cluster0.mqlrz.mongodb.net/pj_sgm?retryWrites=true&w=majority",
#             "username": "user1",
#             "password": "start3we",
#             "name": "pj_sgm",
#             "authMechanism": "SCRAM-SHA-1",
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# server단에서 cors-allow-all 
CORS_ORIGIN_ALLOW_ALL = True

# cors resource 특정 도메인 허용
# CORS_ORIGIN_WHITELIST = [
#     'http://127.0.0.1:3000',
# ]
